### ISSUE TITLE
Compatibility with Kong 1.x

### ISSUE THREAD

**Issue by Niko9911** [pantsel/konga#288]
```
KongProxyController request error { name: 'invalid size',
  message: 'size must be an integer between 1 and 1000',
  code: 9 }
```

Using Konga 12.2 and 13.

```
Name        : kong-community-edition
Arch        : noarch
Version     : 1.0.0rc1
Release     : 1
Size        : 46 M
Repo        : installed
From repo   : bintray--kong-kong-community-edition-rpm
Summary     : Kong is a distributed gateway for APIs and Microservices, focused on
            : high performance and reliability.
URL         : https://getkong.org/
License     : ASL 2.0
Description : Kong is a distributed gateway for APIs and Microservices, focused on
            : high performance and reliability.
```

**Comment by Niko9911** [comment]
This is caused by Kong 1.0.0. Please implement support for Kong 1.0.0. Thank You! :1st_place_medal:

**Comment by jeremyjpj0916** [comment]
Same, testing Kong 1.0rc2 some today and see similar errors on all service/route/consumer pages.

![image](https://user-images.githubusercontent.com/31913027/47695137-fc77e400-dbd6-11e8-8681-cafe3cce0e88.png)

My guess is they don't return size in the way the admin API did in the past?

**Comment by jeremyjpj0916** [comment]
@pantsel I know the problem :P , Kong caught onto your max int size tricks and finally now limits you to 1000 per request.

![image](https://user-images.githubusercontent.com/31913027/47695324-f2a2b080-dbd7-11e8-940c-68592f4af54c.png)

Implement something recursive like such as this with the pagination logic(my java client code), and Konga should be all set!:

```
public Consumers getKongConsumers()
    {
        Consumers kongConsumers = new Consumers();

        request = new Request.Builder()
                .header("Authorization", "Bearer " + jwt_token)
                .url(base_admin_url + "/consumers?size=" + MAX_SIZE) //Disable pagination and give us all of it!
                .build();
        try
        {
            response = client.newCall(request).execute();
            //Got a valid response body?
            if(response != null && response.body() != null && response.isSuccessful())
            {
                kongConsumers = gson.fromJson(response.body().string(), Consumers.class);

                if(kongConsumers != null && kongConsumers.getOffset() != null)
                {
                    kongConsumers = getKongConsumers(kongConsumers.getOffset(), kongConsumers);
                }
            }
            else if(response != null && "401".equals(Integer.toString(response.code())))
            {
                renewJwtToken();
                return getKongConsumers();
            }
            else
            {
                //Empty response body, how do we want to handle this
            }
        }
        catch(IOException e)
        {
            //Send an email
            System.out.println("GetKongConsumers" + " Error: " + e.getMessage());
        }

        return kongConsumers;
    }

    public Consumers getKongConsumers(String offset, Consumers kongConsumers)
    {
        Consumers paginatedConsumers = new Consumers();
        try {
            request = new Request.Builder()
                    .header("Authorization", "Bearer " + jwt_token)
                    .url(base_admin_url + "/consumers?offset=" + URLEncoder.encode(offset, "UTF-8") + "&size=" + MAX_SIZE)
                    .build();
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
        try
        {
            response = client.newCall(request).execute();
            //Got a valid response body?
            if(response != null && response.body() != null && response.isSuccessful())
            {
                paginatedConsumers = gson.fromJson(response.body().string(), Consumers.class);
                kongConsumers.getData().addAll(paginatedConsumers.getData());
                if(paginatedConsumers.getOffset() != null)
                {
                    kongConsumers = getKongConsumers(paginatedConsumers.getOffset(), kongConsumers);
                }
            }
            else
            {
                //Empty response body, how do we want to handle this
            }
        }
        catch(IOException e)
        {
            //Send an email
            System.out.println("GetKongConsumers" + " Error: " + e.getMessage());
        }

        return kongConsumers;
    }
```

**Comment by Niko9911** [comment]
Nice! Could you submit PR for this?

**Comment by pantsel** [comment]
@jeremyjpj0916 , yup, noticed that.
I just need to find some time to deal with the fix.
I believe that I will manage to get to it in the next couple of days

**Comment by jeremyjpj0916** [comment]
Excited to test it out! Once you get that out I will continue testing to see if there are any other compatibility issues between Kong 1.0 and the 0.14.x series Konga is already compatible with. Hopefully no more surprises hah.

**Comment by rsbrisci** [comment]
Bumping this for attention, we could also use this feature as Kong 1.0 will be released soon.

**Comment by Niko9911** [comment]
> Kong 1.0 will be released soon.
Isn't it released already? At least on my server Kong 1.0 is waiting to be updated and due this I need to hold that update and make YUM black magic to exclude it from automatic updates.

**Comment by nerdshack604** [comment]
Kong 1.0 GA dropped today  -> https://konghq.com/blog/kong-1-0-ga/

**Comment by wilderchen** [comment]
I have encountered the same problem, anyone can make a PR to solve this issue?

**Comment by dsteinkopf** [comment]
see also #315

**Comment by pantsel** [comment]
Hello guys, I know I've been absent for a while but I had some RL issues to address while waiting for Kong to finalize their 1.x version. 

They've changed a number of things Konga was depending upon, and a s a result, issues like [this](https://github.com/pantsel/konga/issues/288) and  #315 started occuring.

The changes that need to be done to the project in order to achieve 1.x compatibility are not trivial and I need your help to verify that things are working as expected.

Kong 1.x compatibility is being worked on the [next](https://github.com/pantsel/konga/tree/next) branch. Feel free try it out and drop some feedback. If you're using docker, pull `pantsel/konga:next`.

Bare in mind that while there may still be some broken features, the basic Kong API integration should be working just fine.

I'm yet to decide if Konga 0.14.x will be backwards compatible to Kong < 1.x. In case it won't, I will keep a branch of Konga 0.13.x active for the ones that don't want to upgrade their Kong installations just yet.

Cheers.

**Comment by jeremyjpj0916** [comment]
Cross posting from the gitter chat:
"
@pantsel Starting to look good, pagination seems to work on service/routes/plugins pages. Plugins page opening up the schema and fields seem to load fine. Consumers, their acl's and their creds seem to load fine(acl has been needing pagination and searchability for awhile but thats another issue for another day lol). So far 1 bug I have found. If you go into an individual service or an individual route, right now the plugins tab on either loads ALL plugins and not just the ones meant for that given service or route. Probably a simple fix not querying down on what needs to be.
"

**Comment by pantsel** [comment]
@wilderchen , have you noticed something concerning the services entity that is not working as expected on Konga:next due to that change? It seems to be working fine on my end.

**Comment by pantsel** [comment]
@jeremyjpj0916 ,

> right now the plugins tab on either loads ALL plugins and not just the ones meant for that given service or route

This happens because their API stopped working with query strings for some reason.

`/plugins?service_id={service_id}` brings back all plugins

only the `/services/{service_id}/plugins` is valid now.

That's why it's hard to keep up with this project. They're breaking everything on nearly every release with no apparent reason. Almost feels like they're doing it on purpose.

Anyways, I'll make the needed changes, thanks again for the feedback man.

**Comment by pantsel** [comment]
Well IMHO that's neither more 'restful' nor better taxonomy. Quite the contrary, it's ver un-restful, plus apart from the results you can get through paths, now there's no way for example to only get a list of only enabled plugins for a service/route?

That doesn't make sense to me...

**Comment by jeremyjpj0916** [comment]
@pantsel 

Creating an upstream resource seems to work against Kong 1.0, creating a target(ip:port) does not seem to work against Kong 1.0. Also snapshots does not work(but I consider it to be the lowest of priorities). 

-Jeremy

**Comment by jeremyjpj0916** [comment]
Seems my upstream edit throws an interesting error, Images are as follows top / middle / bottom. All I really want is the active healthcheck by itself with no passive healthcheck anyways... Error in red at the top when i tried to save after deleting all the http statuses out of the auto-populated passive healthchecks section after my initial submit:

![topupstreamedit](https://user-images.githubusercontent.com/31913027/50412748-ba97a280-0801-11e9-8027-e4d72fbab443.png)
![middleupstreamedit](https://user-images.githubusercontent.com/31913027/50412749-ba97a280-0801-11e9-8ecd-9dc7017e1b34.png)
![bottomupstreamedit](https://user-images.githubusercontent.com/31913027/50412750-ba97a280-0801-11e9-9b5e-caf2693b8ab9.png)

**Comment by jeremyjpj0916** [comment]
@pantsel I see you did some commits on Christmas 👍 , coding Santa over there lol. So new issue. ACL whitelist to a Service or Route does not seem to work at the moment:

![acltoserviceorroutebroken](https://user-images.githubusercontent.com/31913027/50434545-7f66a380-08d5-11e9-863e-587c9bb2bc88.png)

**Comment by pantsel** [comment]
@jeremyjpj0916 , that was due to the changes on the plugins schema like @wilderchen pointed out.
Just pushed some fixes on the next.

Thanks for the debuging effort man! 

Keep it up.

We're close...

**Comment by jeremyjpj0916** [comment]
@pantsel 

Okay - 
JWT plugin seems fixed
ACL plugin seems fixed
Upstreams stuff seems fixed(edit/passive/active and newer fields)

Broken -
Rate limiting/Correlation Id plugin on service/route (drop down menu options no longer seem to look right, treated as text field currently)

Also the consumers accessible services and routes page does not load still behaving like my prior screenshot.

**Comment by pantsel** [comment]
@jeremyjpj0916 , he consumers accessible services page loads with no probs on my side. 

Can you please check the JS console or the server logs for "ninja" errors :)? 

If there aren't any, it probably means that it takes a lot of time to do the back and forth calculations with Kong (since you have lots of consumer groups). 

If no errors are raised, wait and see if it times out.

**Comment by jeremyjpj0916** [comment]
Its been up doing the dot spin thing for about 10 mins lol. I don't see why it would be the this slow for 500ish things? Nothing in my js logs or server logs, the terminal window for std out errors has nothing either.

1. Get all routes
2. Get all services
3. Get all plugins
4. Pair plugins(acl/auth plugins(jwt/oauth2) to the service/routes by the service/route id tied to them locally in konga as a map.
5. Get consumer, check if he has oauth/jwt/etc creds and get his acl groups.
6. If consumer lacks the creds or lacks the acl whitelist group(or he has the acl blacklist group, I don't use blacklist personally though) against the service/route maps with their resources then not authorized? 

Doing mostly local processing after querying the needed info from Kong on a few calls?

The query for each of those takes a few seconds 2-5 on the host using admin API now but not minutes :p .

I tried snapshots too, didn't seem to work yet either.

**Comment by pantsel** [comment]
I can't seem to be able to reproduce this one man. I'll try to investigate further and get back to you.

**Comment by jeremyjpj0916** [comment]
Its not a big deal yo, the other issues:

Rate limiting/Correlation Id plugin on service/route (drop down menu options no longer seem to look right, treated as text field currently)

and 

Also removing API(Deprecated) from UI will be good, it no longer exists as a resource in 1.0, as well as the consumers accessible API resources page).

For others maybe snapshots are useful too. I do straight C* backups for Kong generally.

Edit - 
The request transformation plugin seems broken from how it use to look as well.

All the ^ are more important anyways :P .

**Comment by pantsel** [comment]
The request transformation plugin also breaks due to the schema changes.

**Comment by jeremyjpj0916** [comment]
@pantsel Right rc2 was an early release candidate and not fully in the image of Kong 1.0 yet. 1.0 drops all support for API resources since they intend for all active Kong users to migrate to service/route model for the 1.0 release(there is a Kong 0.15 which has most of the 1.0 enhancements with support still for deprecated resources).

**Comment by jeremyjpj0916** [comment]
Updating a service does not work either it seems(I tried changing the name), I assume the same error probably applies for updating routes too. Error thrown is this:
![updateserviceerror](https://user-images.githubusercontent.com/31913027/50455529-795cdb00-0946-11e9-9ef6-79be3bd4abd3.png)

**Comment by jeremyjpj0916** [comment]
@pantsel 
Further info on why some of my plugins can't load or add/enable/disable on 1.0, such as:
https://github.com/Optum/kong-upstream-jwt (I think it has to do with being an "empty" schema that has no fields?)

0.14.1 Konga JSON view:
{
  "created_at": 1516388708653,
  "config": {},
  "id": "79b19c0f-43ec-4353-8bb2-2e1e7ea7eafb",
  "name": "kong-upstream-jwt",
  "enabled": true
}

 $ curl localhost:8001/plugins/schema/kong-upstream-jwt
{"fields":{}}
/ $

-----

1.0 Konga JSON view(can't open or disable/enable this plugin under the hood):

{
  "created_at": 1544487594.438,
  "consumer": null,
  "id": "74865976-80ba-4e22-8c56-bd9466841676",
  "service": null,
  "enabled": true,
  "run_on": "first",
  "config": {},
  "route": null,
  "name": "kong-upstream-jwt"
}

/ $ curl localhost:8001/plugins/schema/kong-upstream-jwt
{"fields":{}}
/ $

Error in console when I attempt to disable/enable the plugin:
KongProxyController request error { message: '2 schema violations (created_at: expected an integer; run_on: required field missing)',
  name: 'schema violation',
  fields: 
   { run_on: 'required field missing',
     created_at: 'expected an integer' },
code: 2 

DELETING it does work if its already present(was there before i upgraded to 1.0.

Now after deleting it I manually added it back via CURL with:
curl -X POST http://localhost:8001/plugins --data "name=kong-upstream-jwt"

Maybe a new way you handle plugins in 1.0 causes a breaking issue with empty schema plugins?

**Comment by jeremyjpj0916** [comment]
Also for tracking purposes, maybe this is also why the request transformer plugin your Konga app struggles with: https://github.com/Kong/kong/issues/4137 , seems they have some fixes to make of their own after 1.0 regarding that plugin.

**Comment by dsteinkopf** [comment]
I also have a problem when trying to change the config of one of my [own plugins](https://github.com/dsteinkopf/kong-response-string-replace) via konga. Output in konga log:
```
KongProxyController request error { message: 'schema violation (run_on: required field missing)',
name: 'schema violation',
fields: { run_on: 'required field missing' },
code: 2 }
```
I don't know if it is a problem with my plugin not being upgraded to kong 1.0. It looks like this was the problem - but I haven't found something about this in the plugin documentation. 

Should I open a new issue and/or describe the problem here in more detail? Or does anybody have an idea how to solve this?

**Comment by pantsel** [comment]
@dsteinkopf , I'll try to use your plugin with the changes I'm making for 1.x compatibility. I'll get back to you once i have an answer.

By the way, have you tried with konga:next? @jeremyjpj0916 's custom plugins are tested and working now.

**Comment by dsteinkopf** [comment]
Thank you very much. If I can do anything myself or help you in some way, just let me know.

Yes, I am running kong and konga via docker: konga image is `pantsel/konga:next`. (kong 1.0 image seem not to be available officially - so I am using `dsteinkopf/kong-dup:latest` which in turn uses temporarily `dsteinkopf/kong-1.0:2018-12-27`)

**Comment by pantsel** [comment]
@dsteinkopf , I intsalled your plugin localy using the next branch and it seems to be working fine.

Bare in mind that the next branch now holds  `Konga 0.14.1-rc6`. So, If that's not the version you currently have installed, update your installation.

Let me know what happens.

**Comment by jeremyjpj0916** [comment]
Also seeing a problem around request-termination plugin currently, I cannot disable/enable it. I cannot submit to modify it. Here is its current JSON as seen by Konga:
```
{
  "created_at": 1544487241.556,
  "consumer": null,
  "id": "fe7c76be-ffc6-4732-b6ac-9b6b48b5bee1",
  "service": null,
  "name": "request-termination",
  "run_on": "first",
  "config": {
    "status_code": 200,
    "body": null,
    "content_type": null,
    "message": "Success"
  },
  "route": {
    "id": "c358bcf8-16ea-45cc-a1a3-0e0b6bddd006"
  },
  "enabled": true
}
```

What displays when trying to edit it:
![requestterminationpluginproblems](https://user-images.githubusercontent.com/31913027/50534618-08c8e080-0b37-11e9-9582-79116c96e448.png)

**Comment by dsteinkopf** [comment]
@jeremyjpj0916, this seems to be the same problem as mine (see above).

**Comment by dsteinkopf** [comment]
After manually "PATCH"ing the ip-restriction plugin (from my example above) via curl, this plugin can now be edited via konga. I fetched the plugins from kong via curl, removed `created_at` from it, added `"blacklist": []`. Then `curl --insecure -X PATCH -H "Content-Type: application/json" -H "Accept: application/json" --data $(jq -c . <xxip-restriction.mod) https://kong-ext-zt.steinkopf.net/kong-ext/plugins/a7fc793b-5760-495f-b9a5-54346fab3656 | jq`.

**Comment by pantsel** [comment]
I think it's fixed with the latest commits.
Pull next again and check it out.

Waiting for feedback.

Cheers

**Comment by dsteinkopf** [comment]
(had to wait for build on docker hub)
Sorry, konga footer shows rc8 but I don't see any difference to before: Still `schema violation (run_on: required field missing)` on my own and bundles plugins when they are "old" (migrated from before kong 1.0). Did I make a mistake??

What did you change? (How) can we help?

**Comment by dsteinkopf** [comment]
Good news about the displayed creation date: Seems correct now 👍

**Comment by pantsel** [comment]
@dsteinkopf , I found aproblem with plugin updates that was addressed with commit https://github.com/pantsel/konga/commit/f8a565f6861c5af79037f9b23c0c6cbf04089850 .

Other than that, I cannot reproduce the issue on my env. Maybe because I'm applying the plugins from scratch.

** Long shot: try on different browsers just in case. We stumbled upon a strange cache-related thingy yesterday with @jeremyjpj0916 . **

What If you delete and and re-apply those plugins. 

Everything works OK (create/update)?

**Comment by dsteinkopf** [comment]
You could try to reproduce the problem by installing a 0.14 version, installing some plugin(s) and then upgrading. Of course, this is much hassle...

At the moment I am not at a PC, but I tried changing a plugin via my Phone. Still the same error about run_on :-(

I read about run_on on the kong pages... Question is: Why is it missing when konga is updating the plugin, while it is there in the json kong which sends when fetching the plugin data. Also konga shows it inthe raw view ...

Newly adding a plugin works fine.

Also I cannot see any difference between migrated and new plugins. Both contain the run_on attributes. At least it looks like this.

Could you (or I myself with your help) build a konga version which does more logging? e.g. the jsons kong gets from and sends to kong?

**Comment by pantsel** [comment]
@dsteinkopf , @jeremyjpj0916 
I think I've found the problem while upgrading from `1.0.0rc2` to `1.0.0`.

Patched that and pushed a commit on the next (0.14.1-rc9 now).

Fingers crossed!

**Comment by jeremyjpj0916** [comment]
My update on the progression of this on the next branch:

Everything seems to be great now, have not tested snapshot imports but I see latest issues resolved such as:
1. request termination saves fine now
2. consumer accessible routes page loads properly
3. "bundled" is no longer a required  plugins dependency to see the ^ page or to take snapshots

IMO Konga is ready to expose a full release for 1.0 at this stage. The only caveat it seems to me is that at the moment the request transformation plugin is broken on Kong's end, so Konga can't exactly integrate properly with it yet, but once that done I am sure @pantsel can do a quick fix up for that specific plugin.

EDIT - 

One more bug lol, go to consumers page and try to create an Oauth2.0 token on consumer, you will see a schema violation under "name" in red. I tried a HS256 JWT creation for a consumer and that seems to work though. I only use oauth/jwt creds on consumers so someone else can give the other boring ones (key auth/hmac/basic auth) a go 😆  .

**Comment by pantsel** [comment]
@jeremyjpj0916 , that error was missleading.

The actual error if you check the console is : `redirect_uris: "required field missing"`

According to Kong's docs, the property name is `redirect_uri` but Kong 1.x needs it to be plural?

**Comment by pantsel** [comment]
> And updating migrated existing plugins ip-restriction and acl still results in schema violation (config.blacklist: field required for entity check when updating). I guess this is a problem with the difference between empty/null/whatever and an empty list.

I think that you won't be able to avoid some manual labor like deleting -> re-assigning plugins on this one.

**Comment by dsteinkopf** [comment]
ok. that would be ugly but acceptable... But aren’t you (konga) able to get the schema from the plugins and check if there are any missing attributes?

**Comment by pantsel** [comment]
That's what Konga is doing. The attributes are generated dynamically from the schema.

Still, I don't think that the specific issue  `config.blacklist: field required for entity check when updating` has to do with that.

On my env, those plugins are working with no probs whatsoever so I can't reproduce that error using Kong 1.0.0.

Is there a possibility you had defined `config.blacklist` before upgrading and now you're trying to delete `config.blacklist` and setting only `config.whitelist`?

**Comment by dsteinkopf** [comment]
I did some experiments to check your question about existing `blacklist`.

This is one of my upgraded plugins:

```
# curl --silent --insecure -X GET https://mykonga/kong-ext/plugins/44c111f6-863a-4a42-a269-097f45b2dc79 | tee xxip-restriction_from_kong.json | jq .
{
  "created_at": 1543148192,
  "config": {
    "whitelist": [
      "192.168.40.5",
      "192.168.40.21"
    ]
  },
  "id": "44c111f6-863a-4a42-a269-097f45b2dc79",
  "service": {
    "id": "5e350633-545d-44dd-bdf7-1ac1becca952"
  },
  "enabled": true,
  "run_on": "first",
  "name": "ip-restriction"
}
```

As you can see, `blacklist` is missing here. Kong won't accept this json:

```
# curl --silent --insecure -X PATCH -H "Content-Type: application/json" -H "Accept: application/json" --data @xxip-restriction_from_kong.json https://mykonga/kong-ext/plugins/44c111f6-863a-4a42-a269-097f45b2dc79 | jq
{
  "message": "schema violation (config.blacklist: field required for entity check when updating)",
  "name": "schema violation",
  "fields": {
    "config": {
      "blacklist": "field required for entity check when updating"
    }
  },
  "code": 2
}
```

Then I added an empty `blacklist` to the JSON:

```
jq -c <xxip-restriction_from_kong.json '.config |= .+ { "blacklist":[] }' | tee xxip-restriction_plus_blacklist.json | jq
{
  "created_at": 1543148192,
  "config": {
    "whitelist": [
      "192.168.40.5",
      "192.168.40.21"
    ],
    "blacklist": []
  },
  "id": "44c111f6-863a-4a42-a269-097f45b2dc79",
  "service": {
    "id": "5e350633-545d-44dd-bdf7-1ac1becca952"
  },
  "enabled": true,
  "run_on": "first",
  "name": "ip-restriction"
}
```

This will work then:

```
# curl --silent --insecure -X PATCH -H "Content-Type: application/json" -H "Accept: application/json" --data @xxip-restriction_plus_blacklist.json https://mykonga/kong-ext/plugins/44c111f6-863a-4a42-a269-097f45b2dc79 | jq
{
  "created_at": 1543144592,
  "config": {
    "whitelist": [
      "192.168.40.5",
      "192.168.40.21"
    ],
    "blacklist": []
  },
  "id": "44c111f6-863a-4a42-a269-097f45b2dc79",
  "service": {
    "id": "5e350633-545d-44dd-bdf7-1ac1becca952"
  },
  "enabled": true,
  "run_on": "first",
  "consumer": null,
  "route": null,
  "name": "ip-restriction"
}
```

Now this plugin seems to be correctly upgraded and I am also able to edit it via konga.

So I think, konga should be able to add the `blacklist` by itself. - But I also consider this described method as an acceptable way to upgrade the plugins manually (at least for me).

--

Now I have to look for another plugin in my installation with this problem to create screenshots :-)

**Comment by dsteinkopf** [comment]
This is a screenshot just after pressing "submit":

![image](https://user-images.githubusercontent.com/4188783/50547776-f9ce5500-0c40-11e9-811d-21a784ed6ffe.png)

**Comment by pantsel** [comment]
Ok so the `blacklist` field was not required prior to Kong 1.0.0 and it is now.

It would be helpful ig they had a `required: true` property in the plugins schema but instead they got this:
```
{
    "fields": [
        {
            "whitelist": {
                "elements": {
                    "type": "string"
                },
                "type": "array"
            }
        },
        {
            "blacklist": {
                "elements": {
                    "type": "string"
                },
                "type": "array"
            }
        }
    ]
}
```

No way of knowing if a field is required without per-case monkey-patching which is something I generally try to avoid if I have a better solution.

**Comment by dsteinkopf** [comment]
Yes, you're right. I consider this a bug in this plugin :-( 

The [kong plugin doc](https://docs.konghq.com/1.0.x/plugin-development/plugin-configuration/) says about the `required` attribute in the schema: 

> Default: false. If true, the property must be present in the configuration.

So `required` does NOT say that this field has to be filled (not empty) - it just says it must be *present*. Should we open a bug report in kong?

**Comment by pantsel** [comment]
I'll try to handle it somehow, maybe by populating everything there is in the schema regardless of whether the property exists in their reponse or not

**Comment by dsteinkopf** [comment]
Ok fine. But as you said, this is not the ideal solution...

**Comment by pantsel** [comment]
We work with what we have :)

**Comment by pantsel** [comment]
Strange, that is what Konga is sending to Kong on my env.
As you can see there is no `config.blacklist` defined.
```
{
  "created_at": 1546179319,
  "id": "ddf25733-116d-4dbc-b5a9-490c98b4d04d",
  "service": null,
  "enabled": true,
  "run_on": "first",
  "consumer": null,
  "route": null,
  "name": "acl",
  "config": {
    "whitelist": [
      "test"
    ],
    "hide_groups_header": false
  }
}
```

Still, it updates with no probs.

Question, are you by any chance using Casandra as a datastore? Im using Pg here.

**Comment by dsteinkopf** [comment]
THAT is strange. I am also using kong 1.0.0 which I built myself from https://github.com/Kong/docker-kong (`alpine` directory) because kong 1.0 isn't yet available from https://hub.docker.com/_/kong.

Did you try to use `curl` and `PATCH`  this JSON (without blacklist) ?

And no - I am also using pg.

**Comment by dsteinkopf** [comment]
BTW. What is your knowledge of the transformer plugin problem? (I am currently trying to add a `request-transformer` without success.)

**Comment by pantsel** [comment]
That is a Kong issue. The schema is messed up on 1.0.0
https://github.com/Kong/kong/issues/4137

**Comment by jeremyjpj0916** [comment]
@pantsel Noted on the oauth change here for their docs: https://github.com/Kong/docs.konghq.com/issues/1092 , if I get time later I will fix it myself, thanks for fixing it in Konga!

**Comment by jeremyjpj0916** [comment]
@pantsel Okay tested OAuth2.0 client cred creation now, seems to be working good. Did some regression testing and it seems the request termination plugin created on a route breaks once again xD -

![requestterminationonroute](https://user-images.githubusercontent.com/31913027/50565581-1ee9c300-0d28-11e9-83d9-4f597b117db3.png)

I can taste the finish lineeeee.

**Comment by jeremyjpj0916** [comment]
Confirmed ^ problem was fixed by the commit. Thx.

**Comment by jeremyjpj0916** [comment]
@pantsel ^ seems to have fixed the issue. I did try a restore snapshot and I have a oauth2 and jwt cred assigned to a user. I didn't restore it to an empty node but just clicked restore on a kong environment that already had that snapshot data and I see these errors:

![image](https://user-images.githubusercontent.com/31913027/50721028-37ebce80-10b0-11e9-8769-1f886fde3faa.png)

I imagine if it successfully checks they are already present it should just count as a success and keep going right and add +1 to the imported row? Since services/plugins/routes/cousmers/acls all did so.

**Comment by jeremyjpj0916** [comment]
Update, now testing 1.0.2, seems the request transformation plugin page works like a charm out of the box 👍 .

**Comment by dsteinkopf** [comment]
@jeremyjpj0916 , I can confirm this.

**Comment by pantsel** [comment]
So I guess we're ready to merge next to master?
I'll do some final testing and publish the new release to master.

**Comment by jeremyjpj0916** [comment]
@pantsel I would say it is certainly good enough to release, I would test snapshots and consumer eligible routes at scale with plugins and all enabled on the routes(see my earlier comment a few up with a snapshot import that failed).

Thanks!

**Comment by amitofile** [comment]
@Niko9911 I got same error on every page services, routes, certificates,

> KongProxyController request error { name: 'invalid size',
>   message: 'size must be an integer between 1 and 1000',
>   code: 9 }

So I changed the value for,
**size : 4294967295** to **999** (in assets/js/app/routes/00_routes.js)
**itemsFetchSize: 4294967295** to **999** (in assets/js/app/core/services/ListConfigService.js)

This fixed the alert and started showing lists.
I hope this is fine.

Kong v1.0.2
konga v0.13.0

**Comment by Niko9911** [comment]
@amitofile  as pantsel said.... It's not about getting one thing working. If I fix that error, there will be 10 things to fix. Please do not spam this ticket. Let's focus developing **full support** for Kong 1.0.

Could you contribute to this issue @amitofile by downloading `next` branch and testing it against some edge cases? Would appropriate it a lot! :1st_place_medal:

**Comment by pantsel** [comment]
Closing this issue due to housekeeping since Konga 0.14.1 is fully compatible with Kong 1,x.

Feel free to reopen if you stumble upon anything weird.
